DROP TABLE IF EXISTS pokemon;

CREATE TABLE IF NOT EXISTS pokemon(
     id INTEGER PRIMARY KEY,
     num TEXT NOT NULL,
     name TEXT NOT NULL,
     height DOUBLE NOT NULL,
     width DOUBLE NOT NULL
);